openapi: 3.0.2
info:
  title: Rack Resiliency Service
  license:
    name: Hewlett Packard Enterprise Development LP
    url: http://www.hpe.com/
  version: 1.0.0
  description: >
    The Rack Resiliency Service (RRS) queries the Kubernetes cluster to provide aggregated zone
    information and detailed critical service status. It gathers node details across various zones
    and presents both high-level summaries and in-depth information for zones and critical services.

    ## Resources

      ### /zones
        Retrieve aggregated zone information including:
          - Management Master Nodes: List of master node names.
          - Management Storage Nodes: List of storage node names.
          - Management Worker Nodes: List of worker node names.
          
        Alternatively, if zones are not configured, one of the following informational messages is returned:
          - "No Zones configured"
          - "No Ceph zones configured"
          - "No K8s topology zones configured"

      ### /zones/{zone_name}
        Retrieve detailed information for a specific zone including:
          - zone_name: The name of the zone.
          - no_of_masters: Number of master nodes.
          - no_of_storage: Number of storage nodes.
          - no_of_workers: Number of worker nodes.
          - nodes: Detailed node data, including status and, for storage nodes, associated OSD details.

      ### /criticalservices
        Retrieve a list of critical services with basic details:
          - name: The service name.
          - namespace: The Kubernetes namespace.
          - type: The service type (e.g., Deployment, StatefulSet, DaemonSet).

      ### /criticalservices/{critical_service_name}
        Retrieve detailed information for a specific critical service including:
          - name: The name of the critical service.
          - namespace: The namespace where the service is deployed.
          - type: The type of the service.
          - pods: An array of pod objects with name and status.
          - services: An array of service names associated with the critical service.

    ## Workflows

      All endpoints in the Rack Resiliency Service API are GET requests, except for the update operation on /criticalservices.

      ### Zone Information Retrieval

        - GET /zones  
          Retrieve aggregated zone configuration. The response includes detailed lists of node names for
          each zone or an informational message if zones are not configured.
          
        - GET /zones/{zone_name}  
          Retrieve detailed information for a specific zone, including node counts and statuses.

      ### Critical Service Information Retrieval

        - GET /criticalservices  
          Retrieve a list of critical services with basic details (name, namespace, type).

        - GET /criticalservices/{critical_service_name}  
          Retrieve detailed information for a specific critical service, including associated pods and service components.

      ### Critical Service Update

        - PATCH /criticalservices  
          Update the critical services configuration. The request body should contain a JSON string in the
          new_services property representing the updated critical services configuration.
servers:
  - url: 'https://api-gw-service-nmn.local/apis/rrs'
    description: The production RRS API server. Accessed from outside the mesh.
paths:
  /zones:
    get:
      summary: Get Zones Configuration
      tags:
        - zones
      description: >
        Returns an object where each key is a zone name and the corresponding value contains:
          - Management Master Nodes: List of master node names.
          - Management Storage Nodes: List of storage node names.
          - Management Worker Nodes: List of worker node names.
        
        Alternatively, if zones are not configured, one of the following informational messages is returned:
          - "No Zones configured"
          - "No Ceph zones configured"
          - "No K8s topology zones configured"
      operationId: getZones
      responses:
        '200':
          description: Zones configuration or an informational message.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ZoneConfiguration'
                  - $ref: '#/components/schemas/InformationResponse'
              examples:
                aggregated:
                  value:
                    rack1:
                      "Management Master Nodes": ["ncn-m001", "ncn-m002"]
                      "Management Storage Nodes": ["ncn-s003"]
                      "Management Worker Nodes": []
                    rack2:
                      "Management Master Nodes": ["ncn-m003"]
                      "Management Storage Nodes": ["ncn-s002", "ncn-s001"]
                      "Management Worker Nodes": ["ncn-w001", "ncn-w003"]
                    rack3:
                      "Management Master Nodes": []
                      "Management Storage Nodes": []
                      "Management Worker Nodes": ["ncn-w002", "ncn-w004"]
                noZones:
                  value:
                    Information: "No Zones configured"
                noCeph:
                  value:
                    Information: "No Ceph zones configured"
                noK8s:
                  value:
                    Information: "No K8s topology zones configured"
        '404':
          description: Zones not found.
          
  /zones/{zone_name}:
    get:
      summary: Get Detailed Zone Information
      tags:
        - zones
      description: >
        Returns detailed information for a specific zone including:
          - zone_name: The name of the zone.
          - no_of_masters: Number of master nodes.
          - no_of_storage: Number of storage nodes.
          - no_of_workers: Number of worker nodes.
          - nodes: An object mapping node roles ("masters", "storage", "workers") to lists of node details.
      operationId: getZoneDetails
      parameters:
        - name: zone_name
          in: path
          required: true
          description: The name of the zone.
          schema:
            type: string
      responses:
        '200':
          description: Detailed information for the specified zone.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZoneDetail'
              examples:
                zoneDetail:
                  value:
                    zone_name: "rack1"
                    no_of_masters: 2
                    no_of_storage: 1
                    no_of_workers: 1
                    nodes:
                      masters:
                        - name: "ncn-m001"
                          status: "Ready"
                        - name: "ncn-m002"
                          status: "Ready"
                      storage:
                        - name: "ncn-s003"
                          status: "Ready"
                          osds:
                            - name: "osd.1"
                              status: "up"
                            - name: "osd.4"
                              status: "up"
                            - name: "osd.7"
                              status: "up"
                            - name: "osd.10"
                              status: "up"
                      workers:
                        - name: "ncn-w001"
                          status: "Ready"
        '404':
          description: Zone not found.
          
  /criticalservices:
    get:
      summary: Get Critical Services
      tags:
        - criticalservices
      description: >
        Returns an object containing a list of critical services with details such as name, namespace, and type.
      operationId: getCriticalServices
      responses:
        '200':
          description: List of critical services.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriticalServicesList'
              examples:
                criticalServices:
                  value:
                    critical-services:
                      - name: "nexus"
                        namespace: "nexus"
                        type: "Deployment"
                      - name: "cray-keycloak"
                        namespace: "services"
                        type: "StatefulSet"
                      - name: "kube-proxy"
                        namespace: "kube-system"
                        type: "DaemonSet"
                      - name: "coredns"
                        namespace: "kube-system"
                        type: "Deployment"
                      - name: "kube-multus-ds"
                        namespace: "kube-system"
                        type: "DaemonSet"
        '404':
          description: Critical services not found.
    patch:
      summary: Update Critical Services ConfigMap
      tags:
        - criticalservices
      operationId: patchCriticalServices
      description: >
        Updates the critical services configuration. The request body should contain a JSON string in the
        new_services property representing the updated critical services configuration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CriticalServicesPatch'
      responses:
        '200':
          description: ConfigMap updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriticalServicesPatchResponse'
        '404':
          description: Critical services configuration not found.
          content:
            application/json:
              schema:
                $ref: '#/components/responses/NotFound'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InternalServerError'
          
  /criticalservices/{critical_service_name}:
    get:
      summary: Get Critical Service Details
      tags:
        - criticalservices
      description: >
        Returns detailed information for a specific critical service including:
          - name: The name of the critical service.
          - namespace: The namespace of the service.
          - type: The type of the service (e.g., Deployment, StatefulSet, DaemonSet).
          - pods: An array of pod objects with name and status.
          - services: An array of service names associated with the critical service.
      operationId: getCriticalServiceDetails
      parameters:
        - name: critical_service_name
          in: path
          required: true
          description: The name of the critical service.
          schema:
            type: string
      responses:
        '200':
          description: Detailed information for the specified critical service.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriticalServiceDetailResponse'
              examples:
                criticalServiceDetail:
                  value:
                    Critical Service:
                      name: "cray-keycloak"
                      namespace: "services"
                      pods:
                        - name: "cray-keycloak-0"
                          status: "Running"
                        - name: "cray-keycloak-1"
                          status: "Running"
                        - name: "cray-keycloak-2"
                          status: "Running"
                      services:
                        - "cray-keycloak-headless"
                        - "cray-keycloak-http"
                        - "keycloak"
                      type: "StatefulSet"
        '404':
          description: Critical service not found.
          
components:
  schemas:
    ZoneNodes:
      type: object
      properties:
        Management Master Nodes:
          type: array
          items:
            type: string
        Management Storage Nodes:
          type: array
          items:
            type: string
        Management Worker Nodes:
          type: array
          items:
            type: string
    ZoneConfiguration:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ZoneNodes'
    InformationResponse:
      type: object
      properties:
        Information:
          type: string
    ZoneDetail:
      type: object
      properties:
        zone_name:
          type: string
          description: The name of the zone.
        no_of_masters:
          type: integer
          description: Number of master nodes.
        no_of_storage:
          type: integer
          description: Number of storage nodes.
        no_of_workers:
          type: integer
          description: Number of worker nodes.
        nodes:
          type: object
          description: Mapping of node roles to lists of node details.
          properties:
            masters:
              type: array
              items:
                $ref: '#/components/schemas/Node'
            storage:
              type: array
              items:
                $ref: '#/components/schemas/Node'
            workers:
              type: array
              items:
                $ref: '#/components/schemas/Node'
    Node:
      type: object
      properties:
        name:
          type: string
          description: The node's name.
        status:
          type: string
          description: The node's status (e.g., Ready, NotReady).
        osds:
          type: array
          description: List of OSD details (only applicable for storage nodes).
          items:
            $ref: '#/components/schemas/OSD'
    OSD:
      type: object
      properties:
        name:
          type: string
          description: The OSD's name.
        status:
          type: string
          description: The OSD's status (e.g., up, down).
    CriticalServicesList:
      type: object
      properties:
        critical-services:
          type: array
          items:
            $ref: '#/components/schemas/CriticalService'
    CriticalService:
      type: object
      properties:
        name:
          type: string
        namespace:
          type: string
        type:
          type: string
    CriticalServiceDetailResponse:
      type: object
      properties:
        Critical Service:
          $ref: '#/components/schemas/CriticalServiceDetail'
    CriticalServiceDetail:
      type: object
      properties:
        name:
          type: string
        namespace:
          type: string
        pods:
          type: array
          items:
            $ref: '#/components/schemas/Pod'
        services:
          type: array
          items:
            type: string
        type:
          type: string
    Pod:
      type: object
      properties:
        name:
          type: string
        status:
          type: string
    CriticalServicesPatch:
      type: object
      properties:
        new_services:
          type: string
          description: A JSON string containing the updated critical services configuration.
      required:
        - new_services
    CriticalServiceUpdate:
      type: object
      properties:
        namespace:
          type: string
        type:
          type: string
      required:
        - namespace
        - type
    CriticalServicesPatchResponse:
      type: object
      properties:
        added_services:
          type: array
          items:
            type: string
          example: []
        message:
          type: string
          example: "Update successful"
        skipped_services:
          type: array
          items:
            type: string
          example: ["coredns-xxx", "kube-multus-ds"]
  responses:
    NotFound:
      description: Not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    InternalServerError:
      description: Internal server error.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
